### PR TITLE
Install ghostscript

### PR DESCRIPTION
**Pull request by bitomule**
Required for drawText operations in imagemagick/graphicsmagick.

### CODE REVIEW

**Comment by abrongersma** [comment]
Looks like we'll need to add the -y flag not to have the script prompt us if we're ok with the install. Otherwise I'm cool with this.

**Comment by jackboberg** [comment]
maybe just move it to be included with the other `dependent libraries`?

**Comment by tzmanics** [comment]
Hi @bitomule thanks for contributing. Would you be open to moving the `ghostscript` code up into the code with the rest of the `dependent libraries`? https://github.com/onmodulus/docker-build-node/blob/master/bootstrap.sh#L12

Then we can get this merged :)

**Comment by bitomule** [comment]
Like this? https://github.com/onmodulus/docker-build-node/pull/10

**Comment by tzmanics** [comment]
yup! :) moved to #10

**Pull request closed without merging**
